name: "github-actions-cleanup-workflow-runs"
description: "GitHub action to cleanup workflow runs from a repository"
branding:
  color: "green"
  icon: "book-open"
inputs:
  DRY_RUN:
    description: "Whether to run the action in dry-run mode <true|false>"
    type: string
    default: "true"
    required: false
  DELETE_OLDER_THAN:
    description: "The age of deployments to delete (in days)"
    type: string
    default: "7"
    required: false
  BRANCH_NAME:
    description: "The branch name. Empty means all branches."
    type: string
    required: false
  WORKFLOW_FILE:
    description: "The workflow file name (e.g. workflow.yaml). Empty means all workflows."
    type: string
    required: false
  REPO_NAME:
    description: "The repository name (e.g. api)"
    type: string
    default: ${{ github.event.repository.name }}
    required: false
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Cleanup workflow runs"
      shell: bash
      env:
        DRY_RUN: ${{ inputs.DRY_RUN }}
        DELETE_OLDER_THAN: ${{ inputs.DELETE_OLDER_THAN }}
        BRANCH_NAME: ${{ inputs.BRANCH_NAME }}
        WORKFLOW_FILE: ${{ inputs.WORKFLOW_FILE }}
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ inputs.REPO_NAME }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      run: |
        chmod +x ${{ github.action_path }}/cleanup-workflow-runs.sh
        ${{ github.action_path }}/cleanup-workflow-runs.sh
