on:
  label:
    types:
      - created
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  document-github-action:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    name: Document GitHub action
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Generate action docs
        uses: ./
